# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_entry', '0005_auto_20170906_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=45)),
                ('version', models.CharField(default='', max_length=45)),
                ('plates', models.CharField(default='', max_length=12)),
                ('vin', models.CharField(default='', max_length=18)),
                ('engine_number', models.CharField(default='', max_length=18)),
                ('model', models.CharField(max_length=4)),
                ('sub_brand', models.CharField(default='', max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Motos',
                'verbose_name': 'Moto',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleDamages',
            fields=[
                ('entry_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders_entry.EntryOrder')),
                ('observations', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Daños de las motos',
                'verbose_name': 'Daños de la moto',
            },
        ),
        migrations.CreateModel(
            name='MotorcyclePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=72)),
            ],
            options={
                'verbose_name_plural': 'Partes de la Moto',
                'verbose_name': 'Parte de la Moto',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=72)),
            ],
            options={
                'verbose_name_plural': 'Regiones de la Moto',
                'verbose_name': 'Región de la Moto',
            },
        ),
        migrations.CreateModel(
            name='StatusOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Opciones de Estados de las Motos',
                'verbose_name': 'Opciones de Estado de la Moto',
            },
        ),
        migrations.CreateModel(
            name='StatusPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_entry.EntryOrder')),
                ('motorcycle_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.MotorcyclePart')),
                ('status_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.StatusOptions')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=2)),
                ('rim', models.CharField(max_length=1)),
                ('lifetime', models.CharField(max_length=3)),
                ('condition', models.TextField()),
                ('brand', models.CharField(max_length=45)),
                ('motorcycle_damages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.MotorcycleDamages')),
            ],
            options={
                'verbose_name_plural': 'Estado de las llantas',
                'verbose_name': 'Estado de la llanta',
            },
        ),
        migrations.AddField(
            model_name='motorcyclepart',
            name='motorcycle_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.MotorcycleRegion'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='entry_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_entry.EntryOrder'),
        ),
    ]
