# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_auto_20170906_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='entry_order',
        ),
        migrations.AlterField(
            model_name='damagestatusoptions',
            name='status',
            field=models.CharField(choices=[('YS', 'Sí'), ('NO', 'No'), ('WD', 'Con Daños'), ('QU', '1/4'), ('MI', '1/2'), ('ON', '1/1')], default='YS', max_length=2),
        ),
    ]
