# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0003_auto_20170906_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmotorcyclepart',
            name='damage_status_option',
        ),
        migrations.AddField(
            model_name='statusmotorcyclepart',
            name='status',
            field=models.CharField(choices=[('YS', 'Sí'), ('NO', 'No'), ('WD', 'Con Daños'), ('QU', '1/4'), ('MI', '1/2'), ('ON', '1/1')], default='YS', max_length=2),
        ),
        migrations.DeleteModel(
            name='DamageStatusOptions',
        ),
    ]
