branch-defaults:
  aws-s3:
    environment: motosmexico-env-dev
    group_suffix: null
global:
  application_name: motosmexico-env
  branch: null
  default_ec2_keyname: Key-Tesca
  default_platform: Python 3.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
