# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(default='', max_length=120)),
                ('address', models.CharField(default='', max_length=120)),
                ('colony', models.CharField(default='', max_length=120)),
                ('rfc', models.CharField(default='', max_length=13)),
                ('postal_code', models.CharField(default='00000', max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=72)),
                ('phone_1', models.CharField(max_length=14)),
                ('phone_2', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
